services:
  - type: web
    name: activepieces-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AP_FRONTEND_URL
        value: https://activepieces-demo.onrender.com
      - key: AP_WEBHOOK_URL
        value: https://activepieces-demo.onrender.com
      - key: AP_ENCRYPTION_KEY
        generateValue: true
      - key: AP_JWT_SECRET
        generateValue: true
      - key: AP_DB_TYPE
        value: SQLITE3
      - key: AP_CACHE_PATH
        value: /app/cache
      - key: AP_CONFIG_PATH
        value: /app/config
      - key: AP_EXECUTION_MODE
        value: UNSANDBOXED
      - key: AP_QUEUE_MODE
        value: MEMORY
      - key: AP_TELEMETRY_ENABLED
        value: false
      - key: AP_REDIS_URL
        value: redis://localhost:6379
      - key: AP_REDIS_HOST
        value: localhost
      - key: AP_REDIS_PORT
        value: 6379
      - key: AP_DEV_PIECES
        value: "google-sheets,store,schedule,http,gmail,whatsapp,twilio,telegram,postgres,data-mapper,code,pdf-generator,csv,claude,text-helper,loops,webhook,activepieces,google-gemini"
      - key: AP_PIECES_SOURCE
        value: FILE
      - key: AP_PIECES_SYNC_MODE
        value: NONE
      - key: PORT
        value: 80
      - key: AP_POSTGRES_DATABASE
        value: dummy
      - key: AP_POSTGRES_HOST
        value: localhost
      - key: AP_POSTGRES_PORT
        value: 5432
      - key: AP_POSTGRES_USERNAME
        value: dummy
      - key: AP_POSTGRES_PASSWORD
        value: dummy