services:
  - type: web
    name: activepieces-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AP_FRONTEND_URL
        value: https://activepieces-demo.onrender.com
      - key: AP_WEBHOOK_URL
        value: https://activepieces-demo.onrender.com
      - key: AP_ENCRYPTION_KEY
        generateValue: true
      - key: AP_JWT_SECRET
        generateValue: true
      - key: AP_DB_TYPE
        value: POSTGRES
      - key: AP_POSTGRES_DATABASE_URL
        fromDatabase:
          name: activepieces-db
          property: connectionString
      - key: AP_POSTGRES_DATABASE
        value: activepieces
      - key: AP_POSTGRES_HOST
        fromDatabase:
          name: activepieces-db
          property: host
      - key: AP_POSTGRES_PORT
        fromDatabase:
          name: activepieces-db
          property: port
      - key: AP_POSTGRES_USERNAME
        fromDatabase:
          name: activepieces-db
          property: user
      - key: AP_POSTGRES_PASSWORD
        fromDatabase:
          name: activepieces-db
          property: password
      - key: AP_EXECUTION_MODE
        value: UNSANDBOXED
      - key: AP_QUEUE_MODE
        value: MEMORY
      - key: AP_TELEMETRY_ENABLED
        value: false
      - key: AP_REDIS_URL
        value: redis://localhost:6379
      - key: AP_REDIS_HOST
        value: localhost
      - key: AP_REDIS_PORT
        value: 6379
      - key: AP_DEV_PIECES
        value: "google-sheets,store,schedule,http,gmail,whatsapp,twilio,telegram,postgres,data-mapper,code,pdf-generator,csv,claude,text-helper,loops,webhook,activepieces,google-gemini"
      - key: AP_PIECES_SOURCE
        value: FILE
      - key: PORT
        value: 80

databases:
  - name: activepieces-db
    databaseName: activepieces
    plan: free